# Generated by Django 5.0.1 on 2026-04-03 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('profile_image', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'levels',
            },
        ),
        migrations.CreateModel(
            name='ResultIdCounter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('next_num', models.IntegerField(default=37923423)),
            ],
            options={
                'db_table': 'result_id_sequence',
            },
        ),
        migrations.CreateModel(
            name='TestBankCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'test_bank_categories',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('questions_json', models.TextField(default='[]')),
                ('language', models.CharField(default='uz', max_length=10)),
                ('pin', models.CharField(blank=True, max_length=50)),
                ('custom_rules', models.TextField(blank=True)),
                ('exam_mode', models.CharField(default='static', max_length=20)),
                ('bank_category_ids', models.TextField(default='[]')),
                ('bank_question_count', models.IntegerField(default=0)),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='core.appuser')),
            ],
            options={
                'db_table': 'exams',
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='group',
            field=models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.group'),
        ),
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.ForeignKey(db_column='level_id', on_delete=django.db.models.deletion.CASCADE, to='core.level'),
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('answers_json', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_questions_json', models.TextField(default='[]')),
                ('session_questions_json', models.TextField(blank=True, null=True)),
                ('result_public_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('result_verify_secret', models.CharField(blank=True, max_length=128, null=True)),
                ('ai_summary_json', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.appuser')),
            ],
            options={
                'db_table': 'student_exams',
            },
        ),
        migrations.CreateModel(
            name='TestBankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('options_json', models.TextField()),
                ('correct_answer', models.CharField(max_length=500)),
                ('language', models.CharField(default='uz', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='core.testbankcategory')),
            ],
            options={
                'db_table': 'test_bank_questions',
            },
        ),
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField()),
                ('screenshot_url', models.TextField(blank=True)),
                ('exam', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.appuser')),
            ],
            options={
                'db_table': 'violations_log',
            },
        ),
        migrations.CreateModel(
            name='ExamGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='core.group')),
            ],
            options={
                'db_table': 'exam_groups',
                'unique_together': {('exam', 'group')},
            },
        ),
    ]
