# Generated by Django 5.2.12 on 2026-04-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_unban_evidence"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="studentexam",
            index=models.Index(fields=["student", "exam"], name="student_exa_student_446e25_idx"),
        ),
        migrations.AddIndex(
            model_name="violationlog",
            index=models.Index(fields=["student", "exam"], name="violations__student_ea44a9_idx"),
        ),
        migrations.AddIndex(
            model_name="violationlog",
            index=models.Index(fields=["exam", "timestamp"], name="violations__exam_id_ac094a_idx"),
        ),
    ]
