# Generated by Django 5.2.12 on 2026-04-22 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studentexam_proctor_warning_state'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='examretakewindow',
            new_name='exam_retake_exam_id_7fc266_idx',
            old_name='exam_retake_exam_student_idx',
        ),
        migrations.AlterField(
            model_name='examretakewindow',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.appuser'),
        ),
        migrations.AlterField(
            model_name='examstudentexception',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.appuser'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='proctor_last_warning_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='proctor_official_warnings',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unbanevidence',
            name='admin',
            field=models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, related_name='unban_actions', to='core.appuser'),
        ),
        migrations.AlterField(
            model_name='unbanevidence',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.appuser'),
        ),
    ]
