# Generated by Django 5.2.17 on 2026-09-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_face_login_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceipt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
