# Generated by Django 5.2.17 on 2026-09-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_paymentreceipt_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_exam_id', models.IntegerField(db_index=True)),
                ('student_id', models.CharField(db_index=True, max_length=64)),
                ('exam_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_public_id', models.CharField(blank=True, default='', max_length=100)),
                ('snapshot', models.TextField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'student_exam_attempts',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_login_ip',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
