/** Ambiguous room behaviour is handled by the on-site human proctor. */
export const CENTER_IGNORED = new Set([
  'SUSPICIOUS_AUDIO', 'WHISPER_OR_CONVERSATION_SUSPECTED', 'MICROPHONE_MUTED',
  'MOUTH_MOVEMENT_TALKING', 'HAND_GESTURE_SUSPECTED', 'HAND_NEAR_EAR',
  'FORBIDDEN_OBJECT_LAPTOP', 'FORBIDDEN_OBJECT_BOOK', 'MULTIPLE_FACES', 'SIDE_CONVERSATION_SUSPECTED',
  'GAZE_AWAY_LEFT', 'GAZE_AWAY_RIGHT', 'GAZE_AWAY_UP', 'GAZE_AWAY_DOWN',
  'GAZE_DOWN_TOTAL', 'GAZE_SIDE_TOTAL', 'GAZE_ANSWER_PATTERN', 'FACE_TURNED_AWAY',
  'FACE_TOO_FAR', 'FACE_TOO_CLOSE', 'FACE_OFF_CENTER', 'EXCESSIVE_MOVEMENT',
]);
